# Generated by Django 5.1.1 on 2024-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comentario_constelacao_galaxia_perfil_delete_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='perfil/default_profile.jpg', upload_to='perfil/'),
        ),
    ]
