# Generated by Django 5.1.1 on 2024-12-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_perfil_imagem_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagem_perfil',
        ),
    ]
