# Generated by Django 5.1.1 on 2024-12-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_perfil_imagem_perfil'),
    ]

    operations = [
    ]
