# Generated by Django 5.1.1 on 2024-11-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('magnitude', models.FloatField()),
                ('tipo_espectral', models.CharField(max_length=20)),
                ('curiosidades', models.TextField(blank=True, default='Sem curiosidades')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='Usuário Anônimo', max_length=100)),
                ('texto', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
