# Generated by Django 5.1.1 on 2024-11-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_estrela_forum_index_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estrela',
            new_name='Catalogo',
        ),
    ]
