# Generated by Django 5.1.1 on 2024-12-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_estrela_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Constelacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem_url', models.URLField()),
                ('estrelas_notaveis', models.TextField(help_text='Estrelas notáveis dentro da constelação')),
            ],
        ),
        migrations.CreateModel(
            name='Galaxia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem_url', models.URLField()),
                ('distancia', models.FloatField(help_text='Distância em milhões de anos-luz')),
                ('tipo', models.CharField(choices=[('espiral', 'Espiral'), ('eliptica', 'Elíptica'), ('irregular', 'Irregular')], default='espiral', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True)),
                ('imagem_perfil', models.ImageField(blank=True, default='perfil/default_profile.jpg', null=True, upload_to='perfil/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='curiosidades',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='magnitude',
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='tipo_espectral',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='nome',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='descricao',
            field=models.TextField(default='perfil/default_profile.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogo',
            name='imagem_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogo',
            name='tipo',
            field=models.CharField(choices=[('estrela', 'Estrela'), ('planeta', 'Planeta'), ('galaxia', 'Galáxia'), ('constelacao', 'Constelação')], default='galaxia', max_length=50),
        ),
        migrations.AddField(
            model_name='forum',
            name='usuario',
            field=models.ForeignKey(default='perfil/default_profile.jpg', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='constelacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.constelacao'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='galaxia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.galaxia'),
        ),
    ]
