# Generated by Django 5.1.1 on 2024-12-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_perfil_imagem_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, default='perfil/default_profile.jpg', null=True, upload_to='perfil/'),
        ),
    ]
