# Generated by Django 5.1.1 on 2024-12-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20241210_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagem_perfil',
        ),
    ]
